### ISSUE TITLE
Documentation on workflow

### ISSUE THREAD

**Issue by TC72** [apauley/hledger-flow#111]
First of all wanted to say thanks for the great tool. I've recently dipped my toe into using hledger. I've got 2023 and onwards under control but wanted to import a lot of historical data. The system I'd created for myself turned out to be very similar to what `hledger-flow` expects so I decided to give it a shot.

I now have things working but I want to check the workflow I should be using.
With my current system I convert `qif` to `csv` and then import using rules to `journal` files for each month.
I then edit the journal file manually to handle any `expenses:unknown` and add tags to the journal.
If I make a change to the csv file and import again `hledger` will only import the new data thanks to the `.latest` files it stores. If there is new data it will be appended to the journal file, it won't be overwritten.

If I'm understanding things correctly every time I run `hledger-flow import` all my journal files will be created again and my manual edits will be overwritten. I see this option `hledger-flow import --new-files-only` but that doesn't pick up on entries being added to input files.

Any help to get me moving in the right direction would be great.

**Comment by jfly** [comment]
@TC72, I personally make sure there's a rule for *everything*. That can get a bit awkward, but I like that there's nothing precious about my 2-processed and 3-journal directories, I can always recreate them from my csv and rule files.

I have no idea if this is a good long term plan (for example, it means my rules files are going to grow without bound). I'd be quite curious to hear how other people handle this.

**Comment by TC72** [comment]
Thanks for the reply.

There are some things I can't do with rules.
For example if I go on holiday I tag every transaction related to it with `holiday:summer-2023`.
That way I can tag flights, car rental, restaurants and have a total cost for the holiday.

But I go to the same places and a rules file can't handle this without me adding rules to match the exact date and month of each transaction which is a mess.

**Comment by TC72** [comment]
OK, I've got what I needed by actually reading the Full-fledged Hledger.
When I read the documentation in my head "Full-fledged Hledger" was just referring to running Hledger manually.

After reading it I see that I really should be adding rules at the level of matching a single transaction and use the table format for rules to keep this manageable:

```
if|account2|comment
...
2017-10-11.*EMPLOYER INC||per diem for the trip to New York
```

**Comment by japhir** [comment]
One thing that kept confusing me about this though, is that every time I had to enter a specific rule like this I had to look up how that particular CSV file was formatted. I can't just match against the YYYY-MM-DD format because some banks have very different date formats, or put the payee before/after the description etc. This made me have to open the raw CSV, double check the entry, then write the regex to match that line. Am I missing something here?

**Comment by jfly** [comment]
@japhir, I found that quite frustrating as well. I eventually got fed up and opted to write [preprocess scripts](https://github.com/apauley/hledger-flow/#the-preprocess-script) for each of my financial institutions to coerce them all to the same ISO date format.

**Comment by simonmichael** [comment]
In my import process I have started including a standard csv cleaning step, usually a sed filter, that saves to foo.clean.csv before hledger sees it.

**Comment by japhir** [comment]
I just added this [nice dateutils](http://www.fresse.org/dateutils/#dateconv) package with the following example preprocess script:

```bash
#!/usr/bin/bash

cat $1 | dateconv -S -i "%d-%m-%Y" -f "%F" > $2
```

<3
