### ISSUE TITLE
rules lookup should be extended to look for rules in additional paths

### ISSUE THREAD

**Issue by lestephane** [apauley/hledger-flow#21]
Background: I'm defining some rules files for financial institutions that other people may find useful as well (Revolut in EU and soon US, FFB in DE). I would like to share them in GitHub.

Problem: the rules files (.rules, preprocess) must be in the same directory where the yearly sub-directories are located, or in a parent directory. There is no way to 'discover' these files in some other sibling directory that has been fetched from another git repo.

I could use symlinks of course, except that I'm moving to another encryption driver for the statements directory, which does not support symbolic links yet. 

So, there could be one external git repo with rules for many institutions, or one repo per institution. And then hledger-flow must know to look into it.

Maybe a **HLEDGER_RULE_PATH** environment variable?

```
$ cd GitRepos
$ git clone git@github.com:lestephane/hledger-flow-rules.git
$ tree hledger-flow-rules
hledger-flow-rules
├── ffb
│   └── ffb.rules
└── revolut
    ├── revolut.preprocess
    └── revolut.rules

$ cd ~/Finance
$ vim .envrc
...
path_add  HLEDGER_RULE_PATH  ~/GitRepos/hledger-flow-rules

$ tree Finance
import
├── personal
│   ├── ffb
│   │   └── depot
│   │       ├── 1-in
│   │       │   └── 2018
│   │       │       └── 2018.csv
│   ├── revolut
│   │   ├── checking
│   │   │   ├── 1-in
│   │   │   │   └── 2018
│   │   │   │       └── Revolut-EUR-Statement-2018.csv
```

**Comment by apauley** [comment]
Interesting use case, I'll have to think about it some more.

Very nice idea though to have a place where people can share scripts and rules files!
Similar to the example rules files in hledger, but also supporting scripts.
https://github.com/simonmichael/hledger/tree/master/examples/csv

I'm using symlinks to point some of my `preprocess` and `construct` scripts to scripts maintained elsewhere. Haven't considered environments that doesn't have symlinks.

A very hacky workaround for now could be to make your `preprocess` a simple script wrapper that copies the rules file, and then runs the real `preprocess` in the external repo.

**Comment by apauley** [comment]
Another option, instead copying the rules file with a script, could be to have an `include` line in the `hledger-flow` rules file which just points to the path of the external rules file.

**Comment by lestephane** [comment]
I prefer sticking to the hledger feature set rather than complicate your codebase.
include (in the sense of what is described at https://hledger.org/manual.html#include) would work, what about preprocess scripts though?

**Comment by apauley** [comment]
> I prefer sticking to the hledger feature set rather than complicate your codebase.
> include (in the sense of what is described at https://hledger.org/manual.html#include) would work, what about preprocess scripts though?
> 
> (mind you, I only have one preprocess script so far, and I could probably get rid of it)

The preprocess script could be a simple shell script that just runs the one you maintain elsewhere

**Comment by lestephane** [comment]
> The preprocess script could be a simple shell script that just runs the one you maintain elsewhere

Sure, that works too
