### ISSUE TITLE
Smart date should include "last WEEKDAY" and "X days ago"

### ISSUE THREAD

**Issue by timo-a** [apauley/hledger-flow#36]
I would use those a lot...

**Edit:**
I am a new user and enter all data with `hledger add` (on the terminal).
At times I don't ask for a receipt because I can just memorize the price or it's just one item that I buy often.
~4 days later I remember, hey didn't I buy X last week? I think it was Thursday...

What I currently do:
`hledger add`
open external calendar see which date "last Thursday" is and copy the date into the `hledger add` prompt.

I'd like to do:
`hledger add`
Date [2019/04/23]: `last thursday`

I just realized that `tab` fills in the current date, so being able to type in `4 days ago` isn't that urgent, but since `yesterday` works I expect other phrases to work and with tab completion as for yesterday `l[ast] tab th[ursday] tab` and `4 d[ays] tab a[go] tab` would feel more convenient to me.

**Comment by apauley** [comment]
Hi @timo-a, can you describe how you currently use `hledger-flow`, and where these options could be used?

Your commands together with the expected output will be useful to have.

**Comment by apauley** [comment]
Hi @timo-a, I only saw your edit now.

It looks as if you are referring to the [hledger](https://github.com/simonmichael/hledger/) project,
and not `hledger-flow` which is this project.

I can definitely understand that their may be confusion around this.

I would suggest joining the `hledger` mailing list, or to use the `hledger` issue tracker.

http://list.hledger.org/
