### ISSUE TITLE
`hledger: user error CSVError (ParseErrorBundle...` is rather unclear 

### ISSUE THREAD

**Issue by lestephane** [apauley/hledger-flow#49]
(in v0.11.1.2)

I'm experiencing an error importing a CSV, and am at a loss as to whether the problem is in hledger or hledger-flow or my CSV file, or my rules file. The `pstateInput = "..."` part in the error below contains my whole CSV input file, which I cannot quote here because it is huge and contains PII, so i just put `...`

```text
2019-05-08 15:10:48.668158024 EEST	hledger-flow End:   importing '2-preprocessed/2018/2018.csv' using rules file 'bank-account.rules' ExitFailure 1 (0.081442287s)
hledger: user error (CSVError (ParseErrorBundle {bundleErrors = TrivialError 14 (Just (Tokens (59 :| []))) (fromList [Tokens (44 :| []),Label ('e' :| "nd of line"),EndOfInput]) :| [], bundlePosState = PosState {pstateInput = "...", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "import/personal/bank/account/2-preprocessed/2018/2018.csv", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}}))

hledger-flow: an external process exited with exit code 1.
```

The CSV file in question loads without error in Libreoffice

![image](https://user-images.githubusercontent.com/5460884/57375448-1b6aba80-71a6-11e9-9f44-f70a69f0ce4e.png)

In order to rule out whether it's a quoting issue, or a separating character issue, I'd need to know what quoting character and / or separating character was in use. The error and log statement do not say.

The (probably incomplete) rules file:

```text
skip 7

fields Buchungstag,Wertstellung,Buchungstext,Auftraggeber_Beguenstigter,Verwendungszweck,Kontonummer,BLZ,Betrag_EUR,Glaeubiger_ID,Mandatsreferenz,Kundenreferenz

account1 Personal:Assets:DE:Bank:Account

amount EUR %Betrag_EUR

date %Wertstellung
date-format %d.%m.%Y

currency EUR
```

There are also non ascii characters, but that should be no problem in a UTF8 file

```text
<LATIN SMALL LETTER A WITH DIAERESIS> -> ä
<LATIN SMALL LETTER O WITH DIAERESIS> -> ö
<LATIN SMALL LETTER U WITH DIAERESIS> -> ü
```

**Comment by apauley** [comment]
In the short term I would suggest using your existing `preprocess` script to change the separator.
The `preprocess` script is intended to manipulate the format of CSV files, I think this is within the scope of that.

In the long term this would be solved in https://github.com/simonmichael/hledger/issues/868 like you said.
Maybe you could give your opinion on the whitespace separator issue under discussion, and by doing so assist in the completion if that issue?

**Comment by lestephane** [comment]
This issue is more about the clarity of the error message. If the clarity of the message is outside of hledger-flow control, then I need to close this issue and take it up to them. Let me know.

**Comment by apauley** [comment]
@lestephane We can improve our error messages to be as clear as possible as to what is failing and if it is `hledger-flow` or an external program that failed.

But there has been a lot of improvements after 0.11.1.2. Can you try it using 0.12?

I've changed the separators in one of the example input files, and this is what the error looks like in 0.12:

```
$ hledger-flow --version
hledger-flow 0.12.0.0
$ hledger-flow import
Collecting input files...
Found 3 input files in 0.027027743s. Proceeding with import...
hledger: user error (CSVError (ParseErrorBundle {bundleErrors = TrivialError 0 (Just EndOfInput) (fromList []) :| [], bundlePosState = PosState {pstateInput = "", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "/home/andreas/Code/Hledger/hledger-flow-example/import/gawie/bogart/cheque/2-preprocessed/2016/123456789_2016-03-30.csv", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}}))

=== Begin Error: importing 'import/gawie/bogart/cheque/2-preprocessed/2016/123456789_2016-03-30.csv' using rules file 'import/gawie/bogart/cheque/bogart-cheque.rules' ===
External command:
/usr/bin/hledger print --rules-file /home/andreas/Code/Hledger/hledger-flow-example/import/gawie/bogart/cheque/bogart-cheque.rules --file /home/andreas/Code/Hledger/hledger-flow-example/import/gawie/bogart/cheque/2-preprocessed/2016/123456789_2016-03-30.csv --output-file /home/andreas/Code/Hledger/hledger-flow-example/import/gawie/bogart/cheque/3-journal/2016/123456789_2016-03-30.journal
Exit code 1
Error output:
hledger: user error (CSVError (ParseErrorBundle {bundleErrors = TrivialError 0 (Just EndOfInput) (fromList []) :| [], bundlePosState = PosState {pstateInput = "", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "/home/andreas/Code/Hledger/hledger-flow-example/import/gawie/bogart/cheque/2-preprocessed/2016/123456789_2016-03-30.csv", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}}))

=== End Error: importing 'import/gawie/bogart/cheque/2-preprocessed/2016/123456789_2016-03-30.csv' using rules file 'import/gawie/bogart/cheque/bogart-cheque.rules' ===

```

I'm keen to hear any suggestions you have on making our error messages clearer.

Although I don't think I would like to try and interpret the output of external programs to make their messages clearer, for that I'd prefer to go upstream.

**Comment by apauley** [comment]
@lestephane Did you have a look at how the errors are displayed in the latest version? If you think they are fine then we can close this issue, otherwise I'd love to hear your thoughts on how we can improve it.

**Comment by lestephane** [comment]
Let me try just now

**Comment by lestephane** [comment]
The clarity of the error message is not something hledger-flow can do much about, but in the latest version it does at least include the command line that caused the error, which is sufficient for my purpose.

I've since moved away from csv rules file, using mostly awk based construct and preprocess scripts to be fully in control, but the improved logging will no doubt help others. Thanks!
