### ISSUE TITLE
where to put account aliases and type declarations (aka shared journal fragments needed by all journals)?

### ISSUE THREAD

**Issue by lestephane** [apauley/hledger-flow#50]
(in v0.11.1.2)

I need to define two account aliases for accounts that I now use in multiple preprocess and construct files, to shield myself from having to modify multiple locations if I ever need to rename those two accounts (a distinct possibility)

```text
alias aws:personal = Personal:Expenses:Admin:Hosting:AWS
alias aws:businessone = BusinessOne:Expenses:Admin:Hosting:AWS
```

Problem: I don't see the option to create a journal file that is included by all journal files.

There is a `all-years.journal` at the top-level, but that file is generated.

Without support from hledger-flow for adding a global journal, I don't see how to achieve this cleanly. 

I'm going to try to use a yearly pre-import  that is shared in multiple year subdirectories using symlinks, and will report whether that is an acceptable workaround.

btw, I tried running in `--verbose` mode, but the log output does not report any attempt to look for manual pre / post import journal. Anyway, I will try, and will report.

```bash
$ hledger-flow import --verbose 2>&1 | grep -E "_manual_|pre-import|post-import"
(no output)
```

**Comment by lestephane** [comment]
The workaround I have for now is to add my aliases in the `~/.hledger.journal` file

```text
$ cat ~/.hledger.journal 
!include Vault/Finance/all-years.journal
!include Vault/Finance/alias.journal
```

**Comment by apauley** [comment]
I haven't used aliases before, but maybe something to look at.
I've managed to put all my custom `preprocess` and `construct` logic in a single script, and then I symlink each `preprocess` or `construct` script to the single script.

Your `~/.hledger.journal` option seems like a good approach, although you could consider moving/renaming it so that it lives inside your hledger-flow directory (next to `all-years.journal`).
Just so that everything is in one place, and checked into version control etc.

Then you can point your `LEDGER_FILE` env var to this journal file that you manage.

Using the paths in your example it might look something like this:
```
$ cat Vault/Finance/personal.journal
!include all-years.journal
!include alias.journal
```

We could definitely update the docs to mention this use case.
We currently mention `LEDGER_FILE` here:
https://github.com/apauley/hledger-flow#overview-of-the-basic-workflow

I'm open to accepting doc PRs if you're up to it, otherwise I can modify in the next couple of days.

**Comment by apauley** [comment]
With regards to how you tried to look at verbose output but didn't get any output looking for those files:
you should definitely be able to use those files  in `_manual_`, the only weirdness I can think of is that you'll create those per year, and for this case your own top-level journal is probably better suited.

I don't understand why you're not getting any output.

I get lots of output using the same command.
Here it is on the example repo:
```
hledger-flow-example$ hledger-flow import --verbose 2>&1 | grep -E "_manual_|pre-import|post-import"
2019-05-09 21:56:32.350079874 SAST	hledger-flow Looking for possible extra include files for 'import/gawie/bogart/cheque/2016-include.journal' among these 2 options: ["import/gawie/bogart/cheque/2016-opening.journal","import/gawie/bogart/cheque/_manual_/2016/pre-import.journal"]. Found 1: ["import/gawie/bogart/cheque/2016-opening.journal"]
2019-05-09 21:56:32.350118494 SAST	hledger-flow Looking for possible extra include files for 'import/gawie/bogart/cheque/2016-include.journal' among these 2 options: ["import/gawie/bogart/cheque/2016-closing.journal","import/gawie/bogart/cheque/_manual_/2016/post-import.journal"]. Found 0: []
2019-05-09 21:56:32.350318374 SAST	hledger-flow Looking for possible extra include files for 'import/gawie/bogart/2016-include.journal' among these 2 options: ["import/gawie/bogart/2016-opening.journal","import/gawie/bogart/_manual_/2016/pre-import.journal"]. Found 0: []
2019-05-09 21:56:32.350344034 SAST	hledger-flow Looking for possible extra include files for 'import/gawie/bogart/2016-include.journal' among these 2 options: ["import/gawie/bogart/2016-closing.journal","import/gawie/bogart/_manual_/2016/post-import.journal"]. Found 0: []
2019-05-09 21:56:32.350499415 SAST	hledger-flow Looking for possible extra include files for 'import/gawie/2016-include.journal' among these 2 options: ["import/gawie/2016-opening.journal","import/gawie/_manual_/2016/pre-import.journal"]. Found 0: []
2019-05-09 21:56:32.350524265 SAST	hledger-flow Looking for possible extra include files for 'import/gawie/2016-include.journal' among these 2 options: ["import/gawie/2016-closing.journal","import/gawie/_manual_/2016/post-import.journal"]. Found 0: []
2019-05-09 21:56:32.350679575 SAST	hledger-flow Looking for possible extra include files for 'import/2016-include.journal' among these 2 options: ["import/2016-opening.journal","import/_manual_/2016/pre-import.journal"]. Found 0: []
2019-05-09 21:56:32.350702375 SAST	hledger-flow Looking for possible extra include files for 'import/2016-include.journal' among these 2 options: ["import/2016-closing.journal","import/_manual_/2016/post-import.journal"]. Found 0: []
```

**Comment by apauley** [comment]
Can you run it with the `--show-options` flag and paste the options?

Also, just an FYI, when you upgrade to 0.12 you'll see that some of the command-line options moved from sub-commands to rather be part of the main options.

Use `--help` for details.

**Comment by lestephane** [comment]
Sure, when time allows I'll add a "account aliases" documentation section.

Something's up with the verbose output, I did get the _update_ log entries on *some* import runs, but not others. Still trying to get the reproduction, then I'll file a separate issue for that.

**Comment by lestephane** [comment]
This question also becomes relevant for account type declarations. These I would like to only specify in one place. I currently have an includes.journal at the top-level (one level above `import`), then I have a `generate-yearly-journals.sh` which creates, for each closed year, a YYYY.journal with

```text
# YYYY.journal
!include ../includes.journal
!include YYYY-include.journal
```
```text
# includes.journal
!include accounts.journal
!include invariants.journal
!include autopostings.journal
```

The shared include would be the place for:
- account aliases
- account type declarations
- commodity formats
- autoposting rules & transaction modifiers (maybe, read on)

I'll move the subject of autoposting to a separate issue however, because there is a need for 'looking at' and version controlling the rewritten transactions (for human review) which is currently not met.

**Comment by apauley** [comment]
@lestephane Are you still up for the account aliases doc section?

**Comment by lestephane** [comment]
I've not yet understood how to use account aliases effectively, so that fell by the wayside, but this issue remains valid for account type declarations, currency formats, shared stuff. I could document how to do that, but i'm still busy ingesting my statements and doing reporting for fiscal year 2018 (in two different countries), so I won't be able to tackle it just yet. I've explained the basic mechanism [in this comment](https://github.com/apauley/hledger-flow/issues/50#issuecomment-497257890), and am going to enrich it just now

**Comment by apauley** [comment]
I noticed this issue while looking through past issues, and I think I can make some improvements without too effort.

Relevant hledger docs:
https://hledger.org/journal.html#directives

I have some code in master (currently unreleased) which looks for a `directives.journal` in the base directory, and includes it in the top-level all-years.journal if it exists:

```$ cat all-years.journal
### Generated by hledger-flow - DO NOT EDIT ###

!include directives.journal
!include import/all-years.journal
```

This should work as a place where you can put account aliases and any other directives that are globally applied, and you're using the top all-years.journal as your LEDGER_FILE

It still doesn't cater for the use case you mentioned where you're using one of the yearly include files for queries.
I could look for the existence of this `directives.journal` in deeper levels as well - although I'm not sure what hledger does if directives are included multiple times.

**Comment by simonmichael** [comment]
Warning, some directives have limited scope - see the "Can affect" column at that link - and might need to be in the topmost file to affect everything.

**Comment by apauley** [comment]
Thanks @simonmichael, I didn't notice the "Can effect" column until you mentioned it here - I missed that there's a scrollbar for that table. I'll play with it until I understand how it works.

**Comment by simonmichael** [comment]
It's a bit non obvious (both scroll bar and directive behaviours - feel free to ask for more clarity on irc.)
