### ISSUE TITLE
Parsing of PDF statements, and multi-currency accounts

### ISSUE THREAD

**Issue by edwintorok** [apauley/hledger-flow#70]
**Is your feature request related to a problem? Please describe.**

My bank only provides CSV/QIF/QFX statements for recent transactions on current accounts, but not savings accounts.
Historic transactions are available as:
* PDFs containing transaction history with running balance
* PDF for individual transaction events between internal/external accounts, called "advice confirms"
* `.xls` for stock&shares accounts

Luckily the PDFs are very regular, and by using `pdfotext` and `awk` I can "infer" a CSV out of it ... most of the time. `.xls` can be converted to `.csv` with `ssconvert`.

I opened this feature request based on https://news.ycombinator.com/item?id=20024633

**Version and Runtime Information**

Please mention the version number of `hledger-flow` you are using:
```
$ hledger-flow --version
hledger-flow 0.12.2.99 linux x86_64 ghc 8.6
```

Is this the [latest version](https://github.com/apauley/hledger-flow/releases)?

No.

**Our Example Statements Repository**

FYI, we have a repo with some example transactions which you can use to run `hledger-flow` on:
https://github.com/apauley/hledger-flow-example

Can you give examples of what you would like by running `hledger-flow` on these files?
N/A

**Describe the solution you'd like**

Would be useful to have:
* some way of determining the sign of a transaction based on a field, I currently have to match on DEBIT/CREDIT in my rules file and swap `account1` with `account2` accordingly. I tried using `amount-in` and `amount-out`, but apparently these cannot appear only inside an `if` statement. Would be nice if there was a conditional in the CSV rules file that could reverse the sign of a transaction.
* support for `account3` in csv rules. investment tracking would require 3 accounts, see https://hledger.org/Track-investments.html with just 2 accounts "we have violated the double-entry principle and created money out of nowhere.", however CSV rules only support 2 accounts currently
* some way of recording unrealized gains/loss when handling multiple currencies, see:
https://github.com/adept/full-fledged-hledger/wiki/Investments-easy-approach#recording-valuations. This would need something that can generate transactions based on prices. See https://github.com/apauley/hledger-flow/issues/69 for support of prices
* support fields with default values in CSV rules. See  my awk scripts below, often some fields are empty, meaning that they have the same value as the previous non-empty field (this often happens for dates)
* make it easy to record a currency and an exchange rate for multi-currency transactions inside CSV rule conditionals. Currently I have to calculate the final amount in awk, I think I was not able to do this with just CSV rules due to the lack of support for rounding.

* have some built-in support for tracking transactions between 2 of my own accounts, where I have:
 ** an entry in account X saying I did a transaction with reference Z
 ** an entry in account Y saying I did a transaction with reference Z (if an internal account, missing if external)
 ** an entry in my "advice confirms" transaction list saying I transfered something between 2 accounts with reference Z (sometimes ambigous as it doesn't list both account numbers) 
What I currently do here is to have:
```
current account -> assets:transfers:%ref
assets:transfers:%ref -> assets:transfers:loyisa:%ref
assets:transfers:loyisa:%ref -> assets:isa:loyisa
```
This is great for debugging why a certain transaction reference is not balanced (e.g. due to a mistake in my import script, or a missing statement), should there be a builtin way of handling these?

I'd welcome any other suggestion you may have on how to simplify the conversion process I've shown below. What I have now works though, took a while to get here though.

**Describe alternatives you've considered**
Here is a quick and dirty scripts I'm using right now, there's got to be a better way:
```
$ cat current/preprocess.sh
if [ $(basename -s .pdf "$1") = $(basename "$1") ]; then
    cp "$1" "$2"
else
    pdftotext -nopgbrk -fixed 6 "$1" - | awk -f $(dirname $(realpath "$0"))/preprocess.awk >"$2"
fi
```

```
$ cat current/preprocess.awk
BEGIN { OFS=","; FIELDWIDTHS = "9:9 4 1:29 1:15 1:15 1:12" }
/Date.*(Balance|Details)/,/BALANCE CARRIED FORWARD|Summary/ {
    gsub(",","", $0);
    BALANCE = $6;
    if (!(/Balance|Details/)) {
        if (!($1 ~ /^ *$/)) { DATE = $1 };
        if (!($2 ~ /^ *$/)) { TYPE = $2 };
        DESC = DESC " " $3;
        IN = $4;
        OUT = $5;
        if (!(IN ~ /^ *$/ && OUT ~ /^ *$/ && BALANCE ~ /^ *$/)) {
            match(DESC, /ADVICE CONFIRMS +([^ ]*)/, advice)
            ADVICE=advice[1]
            print DATE, TYPE, ADVICE, DESC, IN, OUT, BALANCE
            DESC = ""
        }
    }
}
```

```
cat trade/preprocess
#!/bin/sh
set -eu
T=$(mktemp)
ssconvert -S "$1" "${T}.csv"
cat ${T}.csv.* | grep GBP | grep -v Dividend | sed -e 's/GBP/£/' >"$2"
```

```
cat cc/preprocess
pdftotext -nopgbrk -fixed 4 "$1" - | awk -f $(dirname $(realpath "$0"))/preprocess.awk >"$2"
````

```
TMP=$(mktemp)
pdftotext -layout "$1" - | sed -re 's/ +/ /g' >"$TMP"
(
grep -E "DB Value Date:" "$TMP" | cut -f2 -d:|cut -f2 -d' '
grep -Eo "CR Value Date:.*" "$TMP" | cut -f2 -d:|cut -f2 -d' '
grep -C1 "Account Number" "$TMP" | tail -n1|sed -e 's/^ *//'
cat "$TMP" | grep "your account"|sed -re 's/^.*your account ([^ ]+).*$/\1/'
grep -E "Our Ref:" "$TMP" | cut -f2 -d: |sed -e 's/^ *//'
if grep "ROMANIA" "$TMP" >/dev/null; then
    echo ROMANIA
else
    grep -C1 "Senders Reference:" "$TMP" | tail -n1|sed -e 's/,/ /g' -e 's/^ *//'
fi
grep -C1 "Details of Payment" "$TMP" | tail -n1| sed -e 's/,/ /g'
if grep "ADVICE OF CREDIT" "$TMP" >/dev/null; then
    echo "CREDIT"
    grep -Eo "Amount Credit:[^0-9]+[0-9.]+" "$TMP" | cut -f2- -d:
    grep -Eo "Amount Received:[^0-9]+[0-9.]+" "$TMP" | cut -f2- -d:
elif grep "ADVICE OF DEBIT" "$TMP" >/dev/null; then
    echo "DEBIT"
    grep -Eo "Amount Debited:[^0-9]+[0-9.]+" "$TMP" | cut -f2- -d:
    grep -Eo "Original Amount:[^0-9]+[0-9.]+" "$TMP" | cut -f2- -d:
else
    echo "UNKNOWN TYPE" >&2
    exit 1
fi
grep -Eo "Charges:[^0-9]+[0-9.]+" "$TMP" | cut -f2- -d:
) | sed -e 's/GBP/£/g' -e 's/EUR/€/g'| paste -s -d, >"$2"
ER=$(grep -Eo "Exchange Rate:.*" "$TMP"|cut -f2 -d:|sed -e 's/^ *//')
if grep "ADVICE OF CREDIT" "$TMP" >/dev/null && grep "40XXXXXXXXXXXX" "$TMP" >/dev/null && grep Apr "$TMP" >/dev/null && [ -n "$ER" -a "$ER" != "1.00000000" ]; then
(
   # only have statements for 1 side of the transaction here between 2 accounts
   # have to synthesize the other side based on the exchange rate
    grep -E "DB Value Date:" "$TMP" | cut -f2 -d:|cut -f2 -d' '
    grep -Eo "CR Value Date:.*" "$TMP" | cut -f2 -d:|cut -f2 -d' '
    echo
    echo "40YYYYYYYYYYY DEBIT"
    grep -E "Our Ref:" "$TMP" | cut -f2 -d: |sed -e 's/^ *//'
    echo
    echo autogenerated based on exchange rate
    echo "DEBIT"
    AMOUNT=$(grep -Eo "Amount Credit:[^0-9]+[0-9.]+" "$TMP" | cut -f2- -d:|sed -e 's/ *GBP *//')
    AMOUNT2=$(zsh -c "zmodload zsh/mathfunc; echo \$(( int($AMOUNT * $ER * 100.0 + 0.5) / 100.0 ))")
    echo "EUR $(printf '%.2f' $AMOUNT2)"
    echo "GBP $AMOUNT"
    grep -Eo "Charges:[^0-9]+[0-9.]+" "$TMP" | cut -f2- -d:
) | sed -e 's/GBP/£/g' -e 's/EUR/€/g' | paste -s -d, >>"$2"
fi
rm "$TMP"
```

Here is how some the rule file for the above preprocess one looks:
```
cat xxxx-advice.rules
fields date, _, dest, beneficiary, ref1, ref2, desc, typ, amount1, amount2, charges
date-format %d-%b-%y

amount %amount2

description %ref1 %ref2 %desc

if
CREDIT
    account2 assets:transfers:%ref1

if
40XXXXXXXXXXX.*CREDIT
    account1 assets:current-eur:edwin:xxxx

if
40YYYYYYYYYYYY.*CREDIT
    account1 assets:transfers:current:%ref1

if
40ZZZZZZZZZZZZ.*CREDIT
    account1 assets:transfers:loyisa:%ref1
    account2 assets:transfers:%ref1

if
ROMANIA
    account2 assets:current:edwin:romania

if
DEBIT
    account1 assets:transfers:%ref1

if
40XXXXXXXXXXX.*DEBIT
    account2 assets:current-eur:edwin:xxxx
    amount %amount2 @@ %amount1
```

**Additional context**

**Comment by lestephane** [comment]
@edwintorok My 2 cents, since I'm not a committer on the project.

The csv rules file format is **not** under the control of hledger-flow, and any change to that format needs to be followed up in the hledger project as separate issue(s). My experience with csv rules is that they're only useful with very simple situations. Of the 23 accounts I manage at the moment, not a single one is using CSV rules. It always ends up being a mixture of preprocess, construct, or both. But the hledger project will benefit from your feedback, and will help make the CSV rules more useful for everyone eventually.

**Comment by apauley** [comment]
@edwintorok The feature requests are well thought out and well explained, but I agree with @lestephane, `hledger-flow` is a workflow on top of `hledger`, and the features you describe really belong in `hledger` directly.

Luckily a lot of what you described, made it into the latest release:
https://hledger.org/release-notes.html

Specifically support for more than 2 accounts in the rules file:
https://hledger.org/csv.html
https://github.com/simonmichael/hledger/issues/627
https://github.com/simonmichael/hledger/pull/1095

This project provides the `preprocess` and `construct` hooks to cater for anything that you would like to do now, but that isn't supported by hledger.
I would say PDF parsing fall under this umbrella. I haven't done any PDF conversions yet, but if I need to I would also consider using `pdftotext` in some of my custom scripts as you described above. Either as a once-off step outside of the workflow, or in a construct script.

I'm going to close this issue for now - given my limited available time and the focus of the project, I don't think that I can push any of these great suggestions forward.

**Comment by lestephane** [comment]
> I would say PDF parsing fall under this umbrella

I use `pdftotext -layout`+ `awk` all over the place in combination with hledger-flow, works well.
