### ISSUE TITLE
Need a way to import only the current year

### ISSUE THREAD

**Issue by lestephane** [apauley/hledger-flow#81]
**Is your feature request related to a problem? Please describe.**

As my full import takes longer and longer, it starts making sense to restrict the years to import. Currently it imports as far back as it finds years. My top 5 time consumers during full import are from past year. 

I would need to import only the current year, and I could revert to full import when I make
a change that influences past journal generation, but only pay that extra time when I do the full import.

I'm reluctant to put actual stats here, because my files contain personal info, but If you need it I can give you an idea of the top 5, which each take a couple minutes, and are all before 2020.

**Comment by apauley** [comment]
This sounds like a good addition to make.

At the moment I'm prioritising #87 before doing any other changes.
It is slow going - I spend most of my after-work time with normal family matters.

**Comment by apauley** [comment]
@lestephane I've added a different performance-related option in #89, which I'm hoping to release later this weekend.
It makes a big difference in my import, and based on what I understand from your setup it might be the generic speed improvement you want.

**Comment by apauley** [comment]
Released as part of [Version 0.14.2](https://github.com/apauley/hledger-flow/releases/tag/v0.14.2.0)
