### ISSUE TITLE
import YY as 20YY

### ISSUE THREAD

**Issue by Abu-Daud** [apauley/hledger-flow#82]
Hi, How do I import Y=20 as 2020?  
When I use %Y it comes across as 0020

OS X
`hledger-flow -v import`

contents of rules file:
`skip 1`

`fields date, description, amount`
`date-format %-m/%-d/%--Y`
`currency $`

error code:
`Exit code 1`
`Error output:`
`hledger: error: could not parse "6/7/20" as a date using date format "%-m/%-d/%--Y"`

**Comment by apauley** [comment]
Hi @Abu-Daud, the rules file is parsed by the upstream [hledger](https://hledger.org/) project, not by `hledger-flow`.

But looking at your issue, it seems that you need a lower-case `y` in your date format.

See https://hledger.org/csv.html#date-format

As a side comment: `hledger-flow` provides you with the preprocess and/or construct hooks if for any reason the standard `hledger` features doesn't work with your input files. With those hooks you'll be able to either convert your input files to some other format that does work well with hledger, or parse the input yourself.
