### ISSUE TITLE
QUESTION: tags, reports, multiple contributors, virtual accounts, how to do it simply?

### ISSUE THREAD

**Issue by ketzacoatl** [apauley/hledger-flow#86]
**Is your feature request related to a problem? Please describe.**

Hi, this is a great project! This has helped me make full-fledged-hledger (and hledger!) significantly more accessible, thank you for that.

Being new to hledger/PTA and hledger-flow, I may just be overlooking how to do what I want to do with existing features. If that is the case, I apologize and would appreciate guidance on what to do.

There are a couple things I would like to do which may or may not be related, so I'll throw them out there together:

* hledger seems to support tags, and they seem useful (maybe not?). Can I use them with `hledger-flow` and csv imports? I tried defining the field in CSV import rules, but it did not seem to work out ok.
* I have a bunch of "projects" each with their own (virtual) accounts and expenses, liabilities, etc, should I keep them in my primary hledger-flow import or should I separate the projects in some fashion? Maybe you have other recommendations for these types of "virtual" accounts?
* I have some use-cases where an "invoice" or "bill" comes in, and then "multiple parties" contribute to those liabilities, though the actual payment of the invoice/bill is separate. I am having a difficult time understanding the clear/obvious way to track this in hledger-flow. For example, when the invoice is received, or a contribution is made, or the bill is actually paid, I am not sure what to put in my CSV for the accounts.
* If I have different expenses go to `expenses:payables:Acme Corp` and `expenses:payables:Pizza Shop` and such, but would also like to say those are associated with a particular project or tag in reports, should I be using tags or some other tricks with accounts?

**Version and Runtime Information**

```
hledger-flow 0.13.2.0
```

**Comment by apauley** [comment]
Hi @ketzacoatl !

Sorry for only getting back to you now. Let me see if I can answer some of your questions.

### Tags

Tags are put into comments, so if you want a rule in your rules file to generate a tag you can do something like this:

```if
An.*Example.*Regex
  comment tagname:tagvalue
  account2 expenses:SomeExpense
```

https://hledger.org/journal.html#tags
https://hledger.org/tags-tutorial.html
https://hledger.org/csv.html

### Projects

I'm assuming you're not talking about bank accounts, those are separated with owner/bank/account structure mentioned in the hledger-flow docs. If your project is something like a business, you probably have a dedicated bank account with its own statements.

Based on what I imagine a project might be, I'd choose specific accounts where I could then just use normal hledger queries to show me the totals I want.

```
if
Example.*Regex1
  account2 expenses:Projects:BikeShed

if
Example.*Regex2
  account2 expenses:Projects:TakeOverTheWorld
```

Then you'll be able to see how much your projects in total cost you, or drill down into a specific project.

### Invoicing

I've never done this, but I see on the upstream hledger project site there is some docs:
https://hledger.org/invoicing.html

I've also seen people mention invoicing on the hledger mailing list:
https://hledger.org/index.html#help

### More Tags

It could be that tags may help you out, but I'm not sure.

I'd suggest trying it out and see.
https://hledger.org/tags-tutorial.html

For questions like these I think you'll probably get much better answers on the hledger mailing list or chat room.
You could also have a look at the ledger-cli mailing list, there's some activity there as well.

**Comment by ketzacoatl** [comment]
Hi @apauley, thank you for your reply.

> Tags are put into comments, so if you want a rule in your rules file to generate a tag

OK, so if I want to use a column in my CSV file for tags, I should have the rules include a comment field and use that. Thank you for clarifying!
