### ISSUE TITLE
when preprocess is called with a $1 that has a .timeclock extension, $2 has a .csv extension  

### ISSUE THREAD

**Issue by lestephane** [apauley/hledger-flow#91]
**Describe the bug**
I use .timeclock files in one of my time 'account' directories where there is a preprocess and a construct script.
The preprocess script is called with $1 = `$filename.timeclock` and $2 = `$filename.csv`. The problem is that my
preprocess script does not alter the format of the file, it just cleans it. I end up with a csv file that is still a timeclock
file, but has a .csv extension.

This triggers an error when in the construct script, i then make use of that file in an `!include` 

```
$ cat construct 
#!/usr/bin/env bash

source common.sh

hledger print -f - <<EOF
$(<"${my_dir}/aliases.journal")
!include ${1}
EOF
```

when the construct script is run with $1 = `$filename.csv`

```
hledger-1.20.2: sorry, CSV files can't be included yet
caught ERR (exit code : 1)
```

This behaviour did not cause any error in the past, hledger would just figure out from the content file what format it's in.
Now the behaviour has changed, and hledger will complain. 

I guess this falls under the discussion of *should preprocess always result in a CSV file*.  Preprocess could well be
a cleanup step that does not change the extension of the file, but then how to signal this?

The workaround is for me to pack all the steps in a single `construct` file.  

**Reproduction**

- Create a `.timeclock` file in 1-in
- Create a process script that only `cat`s $1 to $2
- Create a construct script that feeds `!include $1` to `hledger print -f -` 
- Error: `CSV files can't be included yet`

**Version and Runtime Information**

```
RuntimeOptions {baseDir = "/home/lestephane/Vault/Finance/", importRunDir = "import/special/timespent/hours-in-project/", importStartYear = Nothing, onlyNewFiles = False, hfVersion = "hledger-flow 0.14.2.0 linux x86_64 ghc 8.10", hledgerInfo = HledgerInfo {hlPath = FilePath "/home/lestephane/Finance/hledger", hlVersion = "hledger 1.20.2"}, sysInfo = SystemInfo {os = "linux", arch = "x86_64", compilerName = "ghc", compilerVersion = Version {versionBranch = [8,10], versionTags = []}}, verbose = True, showOptions = True, sequential = True}
```

**Comment by lestephane** [comment]
no longer an issue, I just found this at https://hledger.org/hledger.html#including-other-files

```
include timeclock:path/to/preprocessed.csv
```

**Comment by apauley** [comment]
Glad you found a solution @lestephane! 

I haven't personally needed to save `preprocess` output files in any other format than csv, but I guess it is possible.

We can discuss possibilities if the issue pops up again, and compare it to using `construct` like you mentioned.

**Comment by lestephane** [comment]
FYI, I have an example of where having more control over the extension in preprocess might be nice.  I put invoice PDFs in `1-in`, and the `preprocess` command calls  `pdftotext --layout`. The files you end up with in `2-preprocess` are plain text files, but double-clicking on them (while working on the .awk parsing script for the construct phase) will start Libreoffice.

Not saying it's absolutely needed, just wanting to illustrate.
