### ISSUE TITLE
Question: where to include "meta" statements (`account...`, `commodity format` & `alias`) & prices?

### ISSUE THREAD

**Issue by sbibauw** [apauley/hledger-flow#99]
First, thank you for `hledger-flow`! I really appreciate the opinionated guidance on structure and the help on the non-destructive workflow.

I have a really basic question, but which I really couldn't find any answer about, nor here, nor on [`hledger-flow-example`](https://github.com/apauley/hledger-flow-example), nor on [`full-fledged-hledger`](https://github.com/adept/full-fledged-hledger/):

**Where do you put "meta"/generic statements** that apply to all your hledgering, such as:

    account assets:bank:savings
    account liabilities:bank:creditcard

    alias USD = $
    commodity 
      format  1,000.00 $
    D 1,000.00 $

    include import/prices/YEAR.prices

In my initial, single-file journal workflow, I had a `meta.journal` which included all this and was included from the main journal, but here, I'm struggling to find where it would be appropriate to include it.

Do you use a main journal file besides those created by `hledger-flow`?
Where does `LEDGER_FILE` env constant points to? (= where does `hledger` defaults to without `-f`?)
That seems important to be able to use `hledger` without `-f` or outside its main directory, and so that you can use `hledger add` to add manual transactions directly to the right place (in `owner/_manual_/2021/post-import.journal`, I guess?)

---

Note: I think this basic question (and other similar ones) could (have) be(en) solved by adding more files to `hledger-flow-example`: a `_manual_` directory with some basic examples in `pre-import.journal` and `post-import.journal` (I'm not sure what goes in each), an `import/prices/2016.prices` example and where it is included, some file with the meta statements I'm mentioning, etc. (If it can help you, I can do a PR with these files as soon as I understand the recommended practice on the matter.) 

I'd ideally also include on `hledger-flow-example` a `.gitignore` file: I'm guessing it is not really necessary to version control files that are entirely generated and transitional (e.g., `2-preprocessed/...`)? Do you actually version control both source (`1-in/*.csv`) and generated (`3-journal/*.journal`) files?

And a `README` listing some typical commands you would run within this workflow could be useful as well :-)

**Comment by sbibauw** [comment]
An additional issue linked to this: today, I tried to import a CSV which has a different `decimal-mark` (`,`) than the main journal (`.`). I [saw](https://github.com/simonmichael/hledger/issues/1158) that `hledger` knows how to convert to the default commodity format when it imports, but because `hledger flow import` makes hledger importing it to a file that has none of those meta statements, it doesn't convert it, which is causing a lot of trouble.

**Comment by apauley** [comment]
Hi @sbibauw, thanks for mentioning these issues. I think I have answers to at least some of them, and we should probably update the README with additional info.

About the "meta" statements you mention, this is a glaring gap in the docs:
you can add a `directives.journal` at the top-level directory, and the generated `all-years.journal` should then include it.

```bash
$ cat all-years.journal
### Generated by hledger-flow - DO NOT EDIT ###

!include directives.journal
!include import/all-years.journal
```

I initially added this as part of #50, but left the issue open in case it doesn't solve the issue. There hasn't been further activity on that issue, so I think we can close it and document the `directives.journal`.

My `LEDGER_FILE` environment variable is also pointed this top-level `all-years.journal`. I think this part is mentioned in the README though.

I see you have prices in your meta file. Prices are included separately, and described here:
https://github.com/apauley/hledger-flow#price-files

Can you expand a bit more on the decimal mark issue? I think I've used some preprocess scripts to change the decimal in some files I have, but maybe there's a better way.

**Comment by simonmichael** [comment]
I can't help pointing out that !include is ancient deprecated syntax - the ! Is unnecessary. Just in case you weren't aware. :)

**Comment by apauley** [comment]
> I can't help pointing out that !include is ancient deprecated syntax - the ! Is unnecessary. Just in case you weren't aware. :)

Thanks, I'll have to update the include file generation to use less ancient syntax 😃

**Comment by sbibauw** [comment]
Thank you for the detailed answer @apauley . `directives.journal` works great. I didn't catch the location of `prices/2021/journal.prices`, so thanks for pointing that out. (I really believe that putting a more detailed example on `hledger-flow-example` would help make it a lot clearer for new users: I'll submit a PR there.)

So, there are only 2 things that I'm still wondering:

1. Is there a way to make use of `hledger add` appropriately, so that manually added transactions will go to some `import/owner/_manual_/2021/post-import.journal`? With the current workflow, they are added to `./all-years.journal` and get erased at every run of `hledger-flow`!

2. The decimal mark issue: I have a Paypal CSV with comas as decimal separator:

    "Date","Time","TimeZone","Name","Type","Status","Currency","Gross","Fee","Net","Receipt ID","Balance","Tip"
    "01/06/2021","08:05:16","PDT","The New York Times Co.","PreApproved Payment Bill User Payment","Completed","EUR","-1,00","0,00","-1,00","","10,00",""

The `rules` file contains

    decimal-mark ,

and that works to make sure `hledger` imports it to the journal appropriately:

    2021-06-01 The New York Times Co
        assets:Paypal:eur                €-1,00 = €10,00
        expenses:press                    €1,00

BUT as you can see, the coma decimal mark remains, which causes some problems down the line.
Now, `hledger` is actually supposed to modify the decimal mark to match the one set in the `commodity format` directive, that I've now put in `directives.journal`:

    commodity 
      format  1,000.00 $
    
but in the current `hledger-flow` workflow, at the moment of importing the CSV applying the rules, `hledger` is unaware of the `directives.journal` containing this format and so it does not convert the decimal mark.

Now, I must say that, while I think that it would be great to implement that somehow, for ideal design, I have now found a solution: using the [`paypalcsv` gist](https://gist.github.com/simonmichael/62cc9661569cdea990dc2020ac36582a) by @simonmichael to import Paypal transactions via the Paypal API, the CSV is correctly formatted with a more standard decimal point.

**Comment by simonmichael** [comment]
> On Jun 15, 2021, at 6:49 AM, Serge Bibauw ***@***.***> wrote:
> I have now found a solution: using the paypalcsv gist <https://gist.github.com/simonmichael/62cc9661569cdea990dc2020ac36582a> by @simonmichael <https://github.com/simonmichael> to import Paypal transactions via the Paypal API

Nice, could I ask how you found that ? I had forgotten it.

**Comment by sbibauw** [comment]
> Nice, could I ask how you found that ? I had forgotten it.

I'm pretty sure I found the link to this gist somewhere on your doc site for `hledger`, but now, I've been trying to find it without any luck!

**Comment by apauley** [comment]
> So, there are only 2 things that I'm still wondering:

1. There isn't a built-in way to easily or automatically let the tool choose the manual journal file. Personally I only add transactions manually in a few cases, and then I specify the file I want with my own hands like a cave-man.
 
In my case the `_manual_/YYYY/*-import.journal` just contains more include statements which I use to further organize my journals. So for me personally I don't think it will help that much if a tool picks a `*-import.journal` file for me. Maybe it can help if the tool is smart enough to auto-complete files based on the mentioned include statements. You'll probably use it in different ways though. If you find that this is a place of improvement that will save you lots of time, maybe start thinking about ways you would want to use it.

2. I'll have to play around with this. Maybe I can include `directives.journal` as a parameter to `hledger` when it generates the transactions. I see there are more imrovements similar to this one which I haven't had a chance to look at yet: https://github.com/apauley/hledger-flow/discussions/97

**Comment by sbibauw** [comment]
Thank you for these answers

For `hledger add` and `hledger-iadd`, @simonmichael kindly pointed to the fact that `hledger` accepts multiple `-f` arguments and will add the transactions to the first file. So the solution for adding manual transactions while taking all the history into account is to do something like:

```shell
hledger add -f import/_manual_/2021/post-import.journal -f all-years.journal
```

I understand that, if you can, it is obviously better not to have to add many manual transactions, but I live in a country where many transactions (including important ones, like buying a car or even a house) are still done in cash. Hence the need for it.
I'm not so convinced by the naming of the "pre/post-import.journal" in the case of cash transactions (because they are not pre/post), but that's unimportant.

**Comment by sbibauw** [comment]
I didn't realize that this was a partial duplicate of #50 . Sorry!

**Comment by apauley** [comment]
> I'll have to play around with this. Maybe I can include `directives.journal` as a parameter to `hledger` when it generates the transactions.

@sbibauw Would you mind trying out the [0.15 release](https://github.com/apauley/hledger-flow/releases/tag/v0.15.0) on the Paypal files you mentioned to see if the amount format is now different? I've switched to using `hledger import`, and I'm giving it the `directives.journal` as a parameter, so it should use the commodity formats you declared.

**Comment by apauley** [comment]
> I can't help pointing out that !include is ancient deprecated syntax - the ! Is unnecessary. Just in case you weren't aware. :)

@simonmichael The latest release now generates files without the obsolete `!include` syntax :-)

**Comment by sbibauw** [comment]
> @sbibauw Would you mind trying out the [0.15 release](https://github.com/apauley/hledger-flow/releases/tag/v0.15.0) on the Paypal files you mentioned to see if the amount format is now different? I've switched to using `hledger import`, and I'm giving it the `directives.journal` as a parameter, so it should use the commodity formats you declared.

Yes, it works! I had solved my Paypal issue, but I just noticed today I had this issue in another file, and YES, the 0.15 release changes the amount format in the generated journal files! Thanks a lot for that!
